//
// Created by chaed on 19. 2. 4.
//

#ifndef TETRIS_FIGURE_CLASS_CLIENTCONTROLLER_H
#define TETRIS_FIGURE_CLASS_CLIENTCONTROLLER_H

class ClientController {

};

#endif //TETRIS_FIGURE_CLASS_CLIENTCONTROLLER_H
