//
// Created by chaed on 18. 12. 18.
//

#ifndef TERIS_FIGURE_CLASS_TOPTIONDISPLAY_H
#define TERIS_FIGURE_CLASS_TOPTIONDISPLAY_H

class TOptionDisplay {

};

#endif //TERIS_FIGURE_CLASS_TOPTIONDISPLAY_H
